apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: synergy
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    io.kompose.service: postgres
  sessionAffinity: None
  type: ClusterIP
