apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: plane-ingress
  spec:
    ingressClassName: nginx
    rules:
    - host: plane.apps.ocp4.example.com
      http:
        paths:
        - backend:
            service:
              name: web
              port:
                number: 3000
          path: /
          pathType: Prefix
        - backend:
            service:
              name: api
              port:
                number: 8000
          path: /api
          pathType: Prefix
        - backend:
            service:
              name: api
              port:
                number: 8000
          path: /auth
          pathType: Prefix
        - backend:
            service:
              name: live
              port:
                number: 3000
          path: /live/
          pathType: Prefix
        - backend:
            service:
              name: space
              port:
                number: 3000
          path: /spaces
          pathType: Prefix
        - backend:
            service:
              name: admin
              port:
                number: 3000
          path: /god-mode
          pathType: Prefix
        - backend:
            service:
              name: plane-minio
              port:
                number: 9000
          path: /uploads
          pathType: Prefix
    - host: plane-minio.apps.ocp4.example.com
      http:
        paths:
        - backend:
            service:
              name: plane-minio
              port:
                number: 9090
          path: /
          pathType: Prefix
    - host: plane-rabbitmq.apps.ocp4.example.com
      http:
        paths:
        - backend:
            service:
              name: plane-rabbitmq
              port:
                number: 15672
          path: /
          pathType: Prefix

kind: List
metadata:
  resourceVersion: ""
